### ISSUE TITLE
BeefUp 1.2.0 animation is choppy + Question

### ISSUE THREAD

**Issue by amichel86** [Schascha/BeefUp#11]
Just wanted to let you know that the latest version has a very "choppy" animation when opening an accordion panel. I tried 1.1.7 instead and it works smoothly.

Also, I would like to have a "next" button inside each panel, when I click on it, it opens the next panel. Would you be able to help out because applying is-open dynamically doesn't do the trick haha

Great plugin BTW!

:)

**Comment by chupzzz** [comment]
**Confirm: choppy animation at 1.2.0!** Used 1.1.8 instead - works fine.

**Comment by mpsn** [comment]
Have the same problem since I changed from 1.1.7 to 1.2.0 (need the accessibility options). But the demo on https://schascha.github.io/BeefUp/ works fine with 1.2.0. Any ideas where to search for the problem?

Thanks for this great plugin - the accessibility options are awesome!

**Comment by mpsn** [comment]
I found the cause: Bootstrap sets 
`[hidden] { display: none !important; }`
which is used by Beefup. Setting it simultaneously with the display attribute should fix the problem.

**Comment by Schascha** [comment]
Thanks and sorry for my late response. As a quick fix, I remove the hidden attribute before the open animation.

**Comment by mpsn** [comment]
Thank you!
