### ISSUE TITLE
stayOpen can't select the first item

### ISSUE THREAD

**Issue by ShamimWP** [Schascha/BeefUp#3]
Hi,

When I set stayOpen: 0, it doesn't select the first item and when I set stayOpen: 1 it selects the second item. How can I select the first item of the accordion?

Thanks,

**Comment by Schascha** [comment]
Hi ShamimWP,

thanks for the hint. Sadly there is a bug in the stayOpen conditions. I will fix it soon.

At the moment you can try `stayOpen: ':first'`

Greetings
Sascha
