### ISSUE TITLE
Open through API and 'openSingle: true'

### ISSUE THREAD

**Issue by vijay-vanecha** [Schascha/BeefUp#4]
Nice plugin!

I have three accordion and three buttons. i want to open each accordion on respective button clicked. Also i set the openSingle option true. So when i am clicking buttons, previously opened accordion stays open so there are multiple accordion opens at a time. Is there any solution for that?

Also is there any option for expand all & collapse all?

Thanks.

**Comment by Schascha** [comment]
Hi vijay-vanecha,

Thanks. Maybe this fiddle will help you:

https://jsfiddle.net/cz0jLspL/13/

Greetings
Sascha
