### ISSUE TITLE
Stop toggle of open item

### ISSUE THREAD

**Issue by alib0ng0** [Schascha/BeefUp#5]
Hi there, is there a way to stop the toggling of an open item? stayOpen doesn't seem to work?

i.e. if this is open:
<article class="beefup example-opensingle floor-1 is-open">
...and you click it, it remains open.

If you click another it closes this and opens the other.

Thanks in advance.
Al

**Comment by Schascha** [comment]
Hi Al,

the stayOpen property only blocks close events from other items, as you can see in the "Open single" example. 

Hmmm, I will have a look, if I find a solution for your request.

Thanks,
Sascha

**Comment by alib0ng0** [comment]
Ok many thanks for getting back to me so quickly - let me know when you have a solution.

**Comment by Schascha** [comment]
Maybe this example will solve your issue: 
http://jsfiddle.net/Schascha/cek0g8ah/

You can find the last changes in the develop branch: https://github.com/Schascha/BeefUp/tree/develop/dist/js

**Comment by alib0ng0** [comment]
Absolute legend! thank you so much. (I've spent the past three hours trying to find my own solution).

**Comment by Schascha** [comment]
You're welcome :)
