### ISSUE TITLE
Hash url

### ISSUE THREAD

**Issue by rudranil29** [Schascha/BeefUp#6]
How can I implement beefup accodian using hash value from url

**Comment by Schascha** [comment]
Hi, just add an id to the accordion container and use it as anchor. The hashchange will trigger the open method. You can take a look here: https://jsfiddle.net/Schascha/kovejmab/

**Comment by rudranil29** [comment]
yes what you did I understand.. But I was asking that how can I open accodian from url value
for example:-
url :- www.xyz.com#item1
hitting on this url it will open accodian which have id="#item1".
how can I implement this

**Comment by rudranil29** [comment]
Thanks a lot..
