### ISSUE TITLE
Option to change the position of caret icon.

### ISSUE THREAD

**Issue by Marhc** [Schascha/BeefUp#7]
Hi Schascha,

    Is there any option to change the position of caret icon? For example: align-to-left?
    And how can I style the caret?

**Comment by Schascha** [comment]
Hi Marhc,

sorry, there is no option for the styling. Feel free to customize the Scss (you will find the caret here https://github.com/Schascha/BeefUp/blob/master/src/scss/jquery.beefup.scss#L36-L48) or override the generated CSS.
