### ISSUE TITLE
Start open

### ISSUE THREAD

**Issue by okabak123** [Schascha/BeefUp#8]
I don't think this behavior was mentioned before, sorry if it has.

When using openSingle, I would like to have one of the items start open.

Difference to stayOpen behaviour would be the selected item wouldnt stay open when clicked on other items.

Example (Except in BeefUp, you can close them all if you wanted.):
https://jqueryui.com/accordion/#default

Thanks for the awesome plugin, I will be grateful if you can consider this feature request.

**Comment by Schascha** [comment]
Hi, 

thanks. Take a look at the `selfBlock: true` property. It will prevent the self close event. 

https://jsfiddle.net/Schascha/cek0g8ah/
